[project]
name = "lucas-v2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Tristan", email = "tristan.robet@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "click>=8.5.0",
    "pandas>=3.0.5",
    "requests>=2.34.2",
]

[project.scripts]
lucas-v2 = "lucas_v2:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
